### ISSUE TITLE
csv file issue

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [gopiprasanthpotipireddy/BrainTumorClassification#2]
while converting braintumour dataset to the .csv file the matrices in the columns are converting in to a strings. it is not suitable to read .csv file and train images.

**Comment by gopiprasanthpotipireddy** [comment]
I uploaded a code to convert the dataframe in to hdf5 format which exactly replicates the dataframe in the os file level, from now we can use hdf5 format for fast processing and storing files other than pickle.

**Comment by suni08** [comment]
Hey I think you have commented this line by mistake in BrainTumor_trainBorder.py, please uncomment it
#if np.array(d['image'][i]).shape[0]!= 512 or np.array(d['image'][i]).shape[1]!=512:

**Comment by gopiprasanthpotipireddy** [comment]
yeah, thank you @suni08,uncommented it
