### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by msethupavan** [gopiprasanthpotipireddy/BrainTumorClassification#3]
Segmentation of images is a huge problem...Which part of image and how the image should be  trained

**Comment by gopiprasanthpotipireddy** [comment]
images are in 512*512 format right ,we have to convert them to single column attributes.

for this we can make each point of image an attribute and can make 512*512=262144  attributes and can remove columns with less variance .

for reshaping I used
 **image_train= image_train.reshape(image_train.shape[0],image_train.shape[1]*image_train.shape[2])**
this formula.

**Comment by gopiprasanthpotipireddy** [comment]
with out this complexity we can use the tumorBorder which is a one dimensional array  to train the model,
why because we need only the tumor portion to be captured by the model. think about it once.
