### ISSUE TITLE
Classification of single image

### ISSUE THREAD

**Issue by misbahSaid** [gopiprasanthpotipireddy/BrainTumorClassification#4]
Hi , I m using the samedata yours. Found your repository today. I m using pytorch and I have converted images to tensors. I have trained file saved as .pth . I m working with label as "feature" for classification. Can you help me how to test image from my pretarined .pth file .?

**Comment by gopiprasanthpotipireddy** [comment]
you need to convert train and test data in to the same format . at the time of converting train data you need to convert the test data to the same format.

**Comment by gopiprasanthpotipireddy** [comment]
check this for how to convert train and test at the same time.
https://github.com/gopiprasanthpotipireddy/BrainTumorClassification/blob/master/mat_reader.py

**Comment by gopiprasanthpotipireddy** [comment]
hi @misbahSaid as there is no response from long time closing this issue.
